// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3yxJjSoiTO44UtJizzu-hatD8FaeHBU',
    appId: '1:806753864266:web:bb2719a7d4a9d7a76fb4b3',
    messagingSenderId: '806753864266',
    projectId: 'dharma-lib',
    authDomain: 'dharma-lib.firebaseapp.com',
    storageBucket: 'dharma-lib.appspot.com',
    measurementId: 'G-65TM12S5KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-dLssObNX-SpAEpl_JbkZ4gEZ6J_CM-g',
    appId: '1:806753864266:android:c4abd4ed7df6f3466fb4b3',
    messagingSenderId: '806753864266',
    projectId: 'dharma-lib',
    storageBucket: 'dharma-lib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQhQLE_hGbGeUd5zNJb18t2lGyTtp-kg',
    appId: '1:806753864266:ios:cb22bacd0455ec196fb4b3',
    messagingSenderId: '806753864266',
    projectId: 'dharma-lib',
    storageBucket: 'dharma-lib.appspot.com',
    iosClientId: '806753864266-7irfgcu7ktgmnp540r2469sajskj1qs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharmalib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQhQLE_hGbGeUd5zNJb18t2lGyTtp-kg',
    appId: '1:806753864266:ios:cb22bacd0455ec196fb4b3',
    messagingSenderId: '806753864266',
    projectId: 'dharma-lib',
    storageBucket: 'dharma-lib.appspot.com',
    iosClientId: '806753864266-7irfgcu7ktgmnp540r2469sajskj1qs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharmalib',
  );
}
